'use strict';

/* WARNING: this file is @generated by Express-Micro.
 * Do NOT remove any comments or change the project layout
 * unless you really know what you're doing. Otherwise the
 * generator won't know where to insert new route definitions.
 */

var commons = require('./commons.js')
var express = require('express');

var controller = commons.controller;
var router = new express.Router();

// generator - insert routes here

module.exports = router;
